name: raspi-2_21.lts.1+

on:
  pull_request:
    types: [opened, reopened, synchronize]
    branches:
      - '21.lts.1\+'
  push:
    branches:
      - '21.lts.1\+'
  workflow_dispatch:
    inputs:
      nightly:
        description: 'Nightly workflow.'
        required: true
        type: boolean
        default: false

jobs:
  raspi-2:
    uses: ./.github/workflows/main.yaml
    permissions:
      packages: write
    with:
      platform: raspi-2
      nightly: ${{ github.event.inputs.nightly }}
